### PR TITLE
update to v0.6.3

### PR DESCRIPTION
**Pull request by mfansler**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] ~~Bumped the build number (if the version is unchanged)~~
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Note the license change.

### CODE REVIEW

**Comment by mfansler** [comment]
@conda-forge-admin, please rerender

**Comment by mfansler** [comment]
@JohanMabille @SylvainCorlay please review 🙏

Change Summary:
 - latest version
 - updated build reqs (needed `make`)
 - win tests no longer exit prematurely
 - cmake registers in `share/` instead of `lib/`
 - added myself as maintainer

**Comment by mfansler** [comment]
@conda-forge/core please review.

This feedstock has had failed bot PRs for a couple years. This PR brings it up to date and adds me as a maintainer.

**Comment by JohanMabille** [comment]
Thanks!

**Pull request merged**
